- name: set up pages
  hosts: aap
  tasks:
    - name: Check for the existence of a folder
      ansible.builtin.stat:
        path: /home/rippa/compliance_reports
      register: folder_stat

    - ansible.builtin.include_tasks: tasks/git_push.yml
      when: not folder_stat.stat.exists

    - name: Clone GIT Repository
      ansible.builtin.git:
        repo: git@github.com:rippa86/compliance_reports.git
        dest: /home/rippa/compliance_reports
        clone: no
        update: yes
      when: folder_stat.stat.exists

    - name: set up date var
      ansible.builtin.set_fact:
        date_dir: "{{ ansible_date_time.date }}"

    - name: check if date folder exists
      ansible.builtin.stat:
        path: "/home/rippa/compliance_reports/{{ date_dir }}"
      register: folder_stat2

    - name: folder doesn't exist
      fail:
        msg: problems with git
      when: not folder_stat2.stat.exists

    - name: get all html files
      ansible.builtin.find:
        paths: "/home/rippa/compliance_reports/{{ date_dir }}/"
        patterns: "*.html"
        excludes: "{{ date_dir }}.html"
      register: html_files

    - name: set files list
      ansible.builtin.set_fact:
        html_files: "{{ html_files.files | map(attribute='path') | list }}"

    - name: show files
      ansible.builtin.debug:
        var: html_files

    - name: time to loop and add :)
      include_tasks: tasks/update_report.yml
      loop: "{{ html_files }}"
      loop_control:
        loop_var: html_path
      vars:
        html_path: "{{ html_path }}"



      # - name: Add output directory to git
      #   ansible.builtin.shell: |
      #     git add -A && git commit -m "AAP Job ID {{ tower_job_id }}: Automated by Ansible  " && git push --force
      #   args:
      #     chdir: /home/rippa/compliance_reports/
      #   ignore_errors: true
      #   register: output

    #       ansible.builtin.shell: >
    #   grep -oP 'progress-bar progress-bar-danger" style="width: [0-9.]+%">\K[^<]+' /tmp/openscap/202402250628_results/rhel-db2.html
    # register: filez
      #  - name: try thing
      #community.general.xml:
      #xpath: /html/body/div/div/div[3]/div[3]/div[4]
      #path: /tmp/openscap/202402250628_results/rhel-db2.html
      #content: attribute
      #register: xmlresp
      #ignore_errors: yes
  # - ansible.builtin.shell: >
  #     grep -oP 'progress-bar progress-bar-success" style="width: [0-9.]+%">\K[^<]+' /tmp/openscap/202402250628_results/rhel-db2.html
