- name: Set up AAP Demo
  hosts: rhel-db2.local
  tasks:
    - name: Check for the existence of a folder
      ansible.builtin.stat:
        path: /home/rippa/compliance_reports
      register: folder_stat

    - ansible.builtin.include_tasks: tasks/push.yml
      when: not folder_stat.stat.exists or not folder_stat.stat.isdi

    - name: Clone GIT Repository
      ansible.builtin.git:
        repo: git@github.com:rippa86/compliance_reports.git
        dest: /home/rippa/compliance_reports
        clone: no
        update: yes
      when: folder_stat.stat.exists

    - name: set up date var
      ansible.builtin.set_fact:
        date_dir: "{{ now(utc=true,fmt='%Y%-m%-d%S') }}"

    - name: check if date folder exists
      ansible.builtin.stat:
        path: "/home/rippa/compliance_reports/{{ date_dir }}"
      register: folder_stat
    - name: update structure
      block:
      - name: create new dir
        ansible.builtin.file:
          path: "/home/rippa/compliance_reports/{{ date_dir }}"
          state: directory
          mode: '0755'

      - name: create new index from date
        ansible.builtin.template:
          src: template.html.j2
          dest: "/home/rippa/compliance_reports/{{ date_dir }}/"

      - name: Insert a line after a specific pattern
        lineinfile:
          path: /home/rippa/compliance_reports/index.html
          line: "<li><a href=\"{{ date_dir }}/{{ date_dir }}.html\">{{ date_dir }}</a></li>"
          insertafter: (<!--new-->)

      - name: Add output directory to git
        ansible.builtin.shell: |
          git add -A && git commit -m "RHAAP Job ID {{ tower_job_id }}: Automated by Ansible  " && git push --force
        args:
          chdir: /home/rippa/compliance_reports/
        ignore_errors: true
        register: output
      when: not folder_stat.stat.exists