- name: Set up AAP Demo
  hosts: rhel-db2.local
  tasks:
    - name: Check for the existence of a folder
      ansible.builtin.stat:
        path: /home/rippa/compliance_reports
      register: folder_stat

    - ansible.builtin.include_tasks: tasks/push.yml
      when: not folder_stat.stat.exists or not folder_stat.stat.isdi