- name: create repo
  hosts: aap
  tasks:
    - ansible.builtin.include_tasks: tasks/set_up_httpd.yml

- name: Run Scap Report on Host
  hosts: rhelz
  become: yes
  tasks:
    - name: ping host
      ansible.builtin.ping:
    
    - name: run the openscap report
      ansible.builtin.include_tasks: tasks/execute_openscap.yml
      vars:
        re_run: false