- name: create repo
  hosts: aap
  tasks:
    - ansible.builtin.include_tasks: tasks/git_config.yml

- name: Run Scap Report on Host
  hosts: rhelz
  tasks:
    - name: ping host
      ansible.builtin.ping:
    
    - name: set up vars
      ansible.builtin.set_fact: 
        datetime: "{{ now(utc=true,fmt='%Y%m%d%H%M') }}"
        hostname: "{{ ansible_facts['nodename'] }}"
    
    - name: check fact hostname
      ansible.builtin.debug:
        var: hostname

    - name: create oscap directory
      ansible.builtin.file: 
        path: /tmp/openscap
        state: directory
        mode: '0755'

    - name: create oscap results directoryz
      ansible.builtin.file:
        path: "/tmp/openscap/{{ datetime }}_results"
        state: directory
        mode: '0755'

    # - name: creating files because apparetnly they need to exist
    #   ansible.builtin.file:
    #     path: /tmp/openscap/{{ datetime }}_results/arf.xml
    #     state: touch
    #     mode: u=rw,g=wr,o=r
    
    - name: run scap role d
      ansible.builtin.include_role:
        name: scap
      vars: 
        oscap_hostname: "{{ hostname }}"
        dir_name: "{{ datetime }}"

    - name: clone git directory
      ansible.builtin.include_tasks: tasks/git_clone.yml

    - name: copy results into cloned directory
      ansible.builtin.copy:
        dest: /tmp/openscap/{{ datetime }}_results/
        src: /tmp/openscap/{{ datetime }}_results/{{ item }}
        mode: preserve
      loop:
        - "{{ hostname }}_arf.xml"
        - "{{ hostname }}.html"

    - name: Add output directory to git
      ansible.builtin.shell: |
        git config --global user.name "David"
        git config --global user.email "dripani@gmail.com"
        git add -A && git commit -m "AAP Job ID {{ tower_job_id }}: adding host {{ hostname }} " && git push --force
      args:
        chdir: /home/rippa/compliance_reports/
      ignore_errors: true
      register: output
