- name: Run Scap Report on Host
  hosts: all
  tasks:
    
    - name: ping host
      ansible.builtin.ping:
    
    - name: set up vars
      ansible.builtin.set_fact: 
        datetime: "{{ now(utc=true,fmt='%Y%m%d%H%M') }}"
        hostname: "{{ ansible_facts['nodename'] }}"
    
    - name: check fact hostname
      ansible.builtin.debug:
        var: hostname

    - name: create oscap directory
      ansible.builtin.file: 
        path: /tmp/openscap
        state: directory
        mode: '0755'

    - name: create oscap results directoryz
      ansible.builtin.file:
        path: "/tmp/openscap/{{ datetime }}_results"
        state: directory
        mode: '0755'

    # - name: creating files because apparetnly they need to exist
    #   ansible.builtin.file:
    #     path: /tmp/openscap/{{ datetime }}_results/arf.xml
    #     state: touch
    #     mode: u=rw,g=wr,o=r
    
    - name: run scap role d
      ansible.builtin.include_role:
        name: scap
      vars: 
        oscap_hostname: "{{ hostname }}"
        dir_name: "{{ datetime }}"