- name: create repo
  hosts: aap
  tasks:
  - name: Create a string for a schedule
    ansible.builtin.debug:
      msg: "{{ query('awx.awx.schedule_rruleset', 'none', start_date='1979-09-13 03:45:07') }}"
