- name: create repo
  hosts: aap
  vars:
    inc_host: batman
  tasks:
  # - name: Create a string for a schedule
  #   ansible.builtin.debug:
  #     msg: "{{ query('awx.awx.schedule_rruleset', 'none', start_date='1979-09-13 03:45:07') }}"
  - name:
    set_fact:
      set_rrule: "{{ now(utc=true,fmt='%Y%m%dT%H%M%SZ') }}"
  - name: Create a new token using username/password
    ansible.controller.schedule:
      controller_host: "{{ aap_host }}"
      controller_username: "{{ aap_username }}"
      controller_password: "{{ aap_password }}"
      name: "Self_healing {{ dir_host }}.local"
      validate_certs: false
      state: present
      unified_job_template: "OSCAP Self Healing"
      rrule: "DTSTART:{{ set_rrule }} RRULE:INTERVAL=1;COUNT=1;FREQ=MINUTELY"
      extra_data:
        inc_host: "{{ inc_host }}"
    register: result
  
  - name: set fact for msg
    setfact: 
      scheduled_job: "AAP Job Scheduled: {{ result.name }} URL to Pause or Cancel: https://192.168.64.11:8443/#/templates/job_template/16/schedules/{{ result.id }}"

  