- name: Set up AAP Demo
  hosts: localhost
  tasks:
  - name: install scap packages
    ansible.builtin.include_tasks: tasks/install_packages.yml
    vars:
      package_name:
      - openscap-scanner
      - scap-security-guide
      
    
    