- name: set up pages
  hosts: all
  vars:
    scheduled_job: aaaaa
    inc_sysid: 8935604397648210d781f141f053af6c
    hostname: rhel-db2
  become: yes
  tasks:
  # - name: Replace Pass with Fail for lines containing hostname.local
  #   update_result:
  #     path: /Users/dripani/server3.html
  #     hostname: rhel-db2
  #   register: result
  - name: Fetch file to local machine
    fetch:
      src: "/tmp/openscap/202403020455_results/*.html"
      dest: /tmp/
      flat: yes
    delegate_to: rhel-aap.local

# - name: Copy file to the destination server
#   hosts: destination_server
#   tasks:
#     - name: Copy file from local machine to destination
#       copy:
#         src: "/local/path/for/temp/storage/file.txt"
#         dest: /path/on/destination/server/

  - debug:
      var: result
  # - name: Update ServiceNow ticket to indicate start
  #   servicenow.itsm.api:
  #     instance:
  #       host: "{{ snow_instance }}"
  #       username: "{{ snow_username }}"
  #       password: "{{ snow_password }}"
  #     resource: incident
  #     action: patch
  #     sys_id: "f2863d9797acc210d781f141f053af7c"
  #     data:
  #       work_notes: "AAP has closed this bad boy"
  #       close_code: Resolved by caller
  #       close_notes: resolved by ansible
  #       incident_state: 7
  #   register: snow_var


  # What a shit module
  # - name: Close Incident
  #   servicenow.itsm.incident:
  #     instance:
  #       host: "{{ snow_instance }}"
  #       username: "{{ snow_username }}"
  #       password: "{{ snow_password }}"

  #     state: closed
  #     # requested_by: some.user
  #     close_code: "Closed/Resolved by Caller"
  #     close_notes: "{{ close_notes }}"
  #     # assignment_group: "Software"
  #     number: "{{ inc_number }}"
  #     other:
  #       work_notes: "This incident has been closed by Ansible Automation Platform"
  #       resolution_code: "Resolved by change"