- name: set up pages
  hosts: aap
  vars:
    scheduled_job: aaaaa
    inc_sysid: 8935604397648210d781f141f053af6c
  tasks:
  - name: Update ServiceNow ticket to indicate start
    servicenow.itsm.api:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      resource: incident
      action: Patch
      sys_id: "{{ inc_sysid }}"
      data:
        work_notes: "AAP has rated these defects as Critical. {{ scheduled_job }}"
    register: snow_var