- name: set up pages
  hosts: aap
  vars:
    scheduled_job: aaaaa
    inc_sysid: 8935604397648210d781f141f053af6c
  tasks:
  - name: Close Incident
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      state: closed
      number: "{{ inc_number }}"
      close_code: "Closed/Resolved by Caller"
      close_notes: "{{ inc_host }} is now compliant, Task completed via job ID: {{ tower_job_id }}. Work attached"
      #resolution_code: "Resolved by change"
      other:
        work_notes: "This incident has been closed by Ansible Automation Platform Job ID: {{ tower_job_id }}"
        resolution_code: "Resolved by change"