- name: Generate Fix
  ansible.builtin.shell:
    oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_e8 \
    --fetch-remote-resources {{ file_host}}_arf.xml > {{ file_host}}_fix.sh
  args:
      chdir: /home/rippa/compliance_reports/
  ignore_errors: true
  register: oscap_result
  become: true

- name: Create Incident
  servicenow.itsm.incident:
    instance:
      host: "{{ snow_instance }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    state: new
    short_description: "{{ file_host }}.local - Non Compliant with E8"
    urgency: 2
    impact: 2
    description: 
      "Server in non compliant with Rippa Corp Policy for Essential 8: AAP ID: {{ tower_job_id }} \n 
      Failed: {{ failed_count}} \n Critical Warning {{ crit_count }} Compliance: {{ comp_percent }}% \n
      https://rippa86.github.io/compliance_reports/{{ ansible_date_time.date }}/{{ file_host }} \n
      Self Healing playbook Scheduled: "
    other:
      assigned_to: "Andrew Och"
      caller_id: "AAP"
  register: new_incident

- name: set stats
  set_fact:
    inc_number: "{{ new_incident.record.number }}"
    inc_sysid: "{{ new_incident.record.sys_id }}"

- name: Print Message
  debug:
    var: new_incident.record.number

- name: Insert a line for failure
  ansible.builtin.lineinfile:
    path: "{{ parent_report }}"
    line: '<li><a href="{{ file_host }}.html">{{ file_host }}.local</a><a href="{{ snow_instance }}/now/sow/record/incident/{{ inc_sysid }}"><span class="incident-number"</span>{{ inc_number }}</a><span class="status fail">Fail</span></li>'
    insertafter: (<!-- Inserthere -->)
  