- name: find the file in question 
  ansible.builtin.file:
    path: "{{ file_path }}{{ date_dir }}/{{ dir_host}}_fix.sh" 
    mode: '0755'
  become: true

- name: Run the shell script
  ansible.builtin.shell:
    cmd: ./{{ dir_host}}_fix.sh
    chdir: "{{ file_path }}{{ date_dir }}/"  
  ignore_errors: true
  become: true
  register: shell_results

- name: show results
  ansible.builtin.debug:
    var: shell_results