- name: set up pages
  hosts: aap
  tasks:
  - name: Create Incident
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      state: new
      short_description: "Hi Brian"
      urgency: "3"
      impact: "2"
      description: "I am the batman"
      other:
        assigned_to: "Andrew Och"
        caller_id: ""Abel Tuter"
    register: new_incident

  - name: set stats
    set_stats:
      data:
        inc_number: "{{ new_incident.record.number }}"

  - name: Print Message
    debug:
      var: new_incident.record.number