- name: strip out hostname
  ansible.builtin.set_fact: 
    file_host: "{{ html_path | regex_replace('^.*\\/([^\\/]+)\\.html$', '\\1') }}"
  
- name: find damage done
  ansible.builtin.shell: >
      grep -oP 'progress-bar progress-bar-danger" style="width: [0-9.]+%">\K[^<]+' {{ html_path }}
  register: filez

- name: return filez as a var
  set_fact:
    failed_count: "{{ filez.stdout_lines[0] | regex_search('(\\d+)') | first | int }}"
    high_count: "{{ filez.stdout_lines[1] | regex_search('(\\d+)') | first | int }}"

- name: Check if failed_count is above 10
  debug:
    msg: "Failed count is above 10"
  when: failed_count > 10

- name: Check if high_count is before 4
  debug:
    msg: "High count is before 4"
  when: high_count < 4
  # - ansible.builtin.shell: >
  #     grep -oP 'progress-bar progress-bar-success" style="width: [0-9.]+%">\K[^<]+' /tmp/openscap/202402250628_results/rhel-db2.html